name: Datalink - Load Test

on:
  workflow_dispatch:

env:
    AZURE_WEBAPP_NAME: datalinkdemo
    AZURE_RESOURCE_GROUP: datalink
jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_LOADTEST_CREDENTIALS }}

      - name: Run Azure Load Test
        uses: azure/load-testing@v1.1.25
        with:
          loadtestConfigFile: './load-test/config.yaml'
          loadtestResource: 'DataLinkLoadTesting' 
          resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
          env: |
            [
                {
                  "name": "webapp",
                  "value": "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/"
                }
            ]

      - name: Save Load Test Results
        uses: actions/upload-artifact@v4
        with:
          name: load-test-results
          path: ./load-test/results