name: Datalink - Load Test

on:
  workflow_dispatch:

env:
    AZURE_WEBAPP_NAME: datalinkdemo

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_LOADTEST_CREDENTIALS }}
